locale = "en"
label = "English"
direction = "ltr"
weight = 1

title = "任"

[params]
  dateFormat = "2 January 2006"
  description = "SRE & Infra. Engineer"

[params.author]
  name = "Kevin Ran (任)"
  headline = "SRE & Infrastructure Engineer"
  bio = "New York-based SRE focused on Linux, K8s, and tooling that makes complex systems manageable."
  image = "images/avatar.jpg"
  links = [
    { github = "https://github.com/chr0n1x" },
    { linkedin = "https://www.linkedin.com/in/kevin-ran-b706481a/" },
    { email = "mailto:heilong24@gmail.com" },
    { pencil = "files/resume.pdf" },
  ]
